---
# Debian
- name: Ensure gpg is installed
  apt:
    name: gpg
    state: present
    update_cache: true

- name: Ensure apt-transport-https is installed
  apt:
    name: apt-transport-https
    state: present
    update_cache: true

- name: Check if extra repository is already configured.
  stat: path={{ item.url }}
  register: repositories_status
  when: item.state != 'absent'
  with_items:
    - "{{ repositories }}"

- name: debug
  debug:
    msg: "{{ repositories_status }}"
  when:
    - settings is defined
    - settings.debug

- name: Import GPG key.
  apt_key:
    url: "{{ item.item.gpg_key_url }}"
    state: present
  with_items:
    - "{{ repositories_status.results }}"
  when:
    - not item.stat.exists
  ignore_errors: "{{ ansible_check_mode }}"


# deb http://nginx.org/packages/mainline/{{ ansible_lsb.id|lower }}/ {{ ansible_lsb.codename|lower }} nginx
# deb-src http://nginx.org/packages/mainline/{{ ansible_lsb.id|lower }}/ {{ ansible_lsb.codename|lower }} nginx
- name: "Install extra repository."
  apt_repository:
    repo: "deb {{ item.item.url }} {{ item.item.codename }} {{ item.item.branch }}"
    filename: "{{ item.item.name }}"
    update_cache: true
    state: "{{ item.item.state }}"
  register: result
  # until: 'item.rc == 0'
  retries: 5
  delay: 10
  with_items:
    - "{{ repositories_status.results }}"
  when:
    - not item.stat.exists
